/*
 * This source file was generated by the Gradle 'init' task
 */
package springBoot.proxies;

import springBoot.proxies.classes.Man;
import springBoot.proxies.classes.Person;
import springBoot.proxies.classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;

public class App {

    public static void main(String[] args) {

        Man man = new Man("Ram", 22, "Indian");
        ClassLoader manClassLoader = man.getClass().getClassLoader();
        Class[] interfaces = man.getClass().getInterfaces();
        Person manProxy = (Person) Proxy.newProxyInstance(manClassLoader, interfaces, new PersonInvocationHandler(man));
        manProxy.personName(man.getName());
    }
}
